name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  building:
    name: Building
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly, stable]
        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true
        os:
          # Check compilation works on common OSes
          # (i.e. no path issues)
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: thumbv6m-none-eabi
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: wasm32-unknown-unknown
      - run: cargo install flip-link
      # Build for Pico
      - run: cargo build --all --target thumbv6m-none-eabi
      - run: cargo build --all --release --target thumbv6m-none-eabi
      # Build for WASM
      - run: cargo build --all --target wasm32-unknown-unknown
      - run: cargo build --all --release --target wasm32-unknown-unknown
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          target: thumbv6m-none-eabi
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          target: wasm32-unknown-unknown
      - run: cargo clippy --target thumbv6m-none-eabi --all-features -- --deny=warnings
      - run: cargo clippy --target wasm32-unknown-unknown --all-features -- --deny=warnings
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          target: thumbv6m-none-eabi
      - run: cargo fmt -- --check
